CREATE OR REPLACE PROCEDURE GET_EMPLOYEE_WORKED_HOURS_BETWEEN(employee_id IN NUMBER, start_date IN VARCHAR, end_date IN VARCHAR, worked_hours OUT NUMBER)
AS
BEGIN

	SELECT SUM(WORKED_HOURS) INTO worked_hours
	FROM EMPLOYEE_WORKED_HOURS A
	WHERE A.EMPLOYEE_ID = EMPLOYEE_ID
	AND A.WORKED_DATE BETWEEN TO_DATE(START_DATE, 'yyyy-MM-dd')
	AND TO_DATE(END_DATE, 'yyyy-MM-dd');

END;