-- ----------------------------
-- Table structure for EMPLOYEE_WORKED_HOURS
-- ----------------------------
DROP TABLE "INTERVIEWUSER"."EMPLOYEE_WORKED_HOURS";
CREATE TABLE "INTERVIEWUSER"."EMPLOYEE_WORKED_HOURS" (
  "ID" NUMBER(19,0) VISIBLE DEFAULT "INTERVIEWUSER"."ISEQ$$_73066".nextval NOT NULL,
  "EMPLOYEE_ID" NUMBER(19,0) VISIBLE,
  "WORKED_DATE" TIMESTAMP(6) VISIBLE,
  "WORKED_HOURS" NUMBER(10,0) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for EMPLOYEES
-- ----------------------------
DROP TABLE "INTERVIEWUSER"."EMPLOYEES";
CREATE TABLE "INTERVIEWUSER"."EMPLOYEES" (
  "ID" NUMBER(19,0) VISIBLE DEFAULT "INTERVIEWUSER"."ISEQ$$_73069".nextval NOT NULL,
  "BIRTHDATE" DATE VISIBLE,
  "GENDER_ID" NUMBER(19,0) VISIBLE,
  "JOB_ID" NUMBER(19,0) VISIBLE,
  "LAST_NAME" VARCHAR2(255 CHAR) VISIBLE,
  "NAME" VARCHAR2(255 CHAR) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for GENDERS
-- ----------------------------
DROP TABLE "INTERVIEWUSER"."GENDERS";
CREATE TABLE "INTERVIEWUSER"."GENDERS" (
  "ID" NUMBER(19,0) VISIBLE DEFAULT "INTERVIEWUSER"."ISEQ$$_73072".nextval NOT NULL,
  "NAME" VARCHAR2(255 CHAR) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for JOBS
-- ----------------------------
DROP TABLE "INTERVIEWUSER"."JOBS";
CREATE TABLE "INTERVIEWUSER"."JOBS" (
  "ID" NUMBER(19,0) VISIBLE DEFAULT "INTERVIEWUSER"."ISEQ$$_73075".nextval NOT NULL,
  "NAME" VARCHAR2(255 CHAR) VISIBLE,
  "SALARY" FLOAT(126) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Primary Key structure for table EMPLOYEE_WORKED_HOURS
-- ----------------------------
ALTER TABLE "INTERVIEWUSER"."EMPLOYEE_WORKED_HOURS" ADD CONSTRAINT "SYS_C007420" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table EMPLOYEE_WORKED_HOURS
-- ----------------------------
ALTER TABLE "INTERVIEWUSER"."EMPLOYEE_WORKED_HOURS" ADD CONSTRAINT "SYS_C007419" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table EMPLOYEES
-- ----------------------------
ALTER TABLE "INTERVIEWUSER"."EMPLOYEES" ADD CONSTRAINT "SYS_C007422" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table EMPLOYEES
-- ----------------------------
ALTER TABLE "INTERVIEWUSER"."EMPLOYEES" ADD CONSTRAINT "SYS_C007421" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table GENDERS
-- ----------------------------
ALTER TABLE "INTERVIEWUSER"."GENDERS" ADD CONSTRAINT "SYS_C007424" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table GENDERS
-- ----------------------------
ALTER TABLE "INTERVIEWUSER"."GENDERS" ADD CONSTRAINT "SYS_C007423" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table JOBS
-- ----------------------------
ALTER TABLE "INTERVIEWUSER"."JOBS" ADD CONSTRAINT "SYS_C007426" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table JOBS
-- ----------------------------
ALTER TABLE "INTERVIEWUSER"."JOBS" ADD CONSTRAINT "SYS_C007425" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
